### ISSUE TITLE
Incorrect display of filename in `wf_transfer`

### ISSUE THREAD

**Issue by Rafnuss** [bluegreen-labs/ecmwfr#152]
I really like this feature of showing in the console which code you can run in case the code crash. But there seems to be an issue when using `wf_request_batch`

```r
library(ecmwfr)

request_list = list()

for (i in c(1,2)){
  print(i)
  request_list[[i]] <- list(
    dataset_short_name = "reanalysis-era5-pressure-levels",
    product_type = "reanalysis",
    format = "netcdf",
    variable = "pressure",
    pressure_level = c(1, 2, 3),
    year = "2010",
    month = "1",
    day = "2",
    time = "13:00",
    area = c(1,0,0,1), # N, W, S, E
    target = glue::glue("test_{i}.nc")
    )
    }

ecmwfr::wf_request_batch(
  request_list,
  path = "~/Downloads/"
)
```

This will give you: 

```r
wf_transfer(
  url = 'https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/52df1030-01bd-41b1-802b-7aa8e8754081',
  path = '~/Downloads/',
  filename = '~/Downloads//test_1'
)
```

instead of 

```r
wf_transfer(
  url = 'https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/52df1030-01bd-41b1-802b-7aa8e8754081',
  path = '~/Downloads/',
  filename = 'test_1.nc'
)
```

**Comment by Rafnuss** [comment]
I've been trying to find a fix for this, but I don't fully undestand that is happening. A bad one is to use `basename(file)` in https://github.com/bluegreen-labs/ecmwfr/blob/bd7bf260f14a845e769113fe81d332c7334abd51/R/zzz.R#L237C5-L237C9 but I suspect that this should be dealt with somewhere else?

**Comment by khufkens** [comment]
I'll put it on my todo list. Not a high priority right now though.

**Comment by khufkens** [comment]
fixed as per https://github.com/bluegreen-labs/ecmwfr/commit/6814c80c078d151cee66cf9e138c83a6b37896cd

install from github if it bugs you, will collect a few more improvements before pushing  new release to CRAN

**Comment by Rafnuss** [comment]
I now have no filename at all, e.g., 
```r
  wf_transfer(
   url = 'https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/77f5345c-bada-4d2c-8c0f-288c475635fe',
   path = './data/wind/16CP',
   filename = ''
  )
```

Haven't looked into the code (yet).

**Comment by khufkens** [comment]
The request is always returned, including the status. So you should be able to do:

```r
t = wf_request(r, transfer = FALSE)
download_url  = t$get_url()
```

I'll look into things tomorrow. Since the migration to the V2 API I haven't been using it much, the whole thing was such a mess I was seriously put off. Not sure if you managed to navigate the new formatting, or if you fall back to the legacy one. Anyway, it messed up so much of my workflow that I was rather put off of things.

**Comment by Rafnuss** [comment]
Even with `wf_request_batch()`? Don't you need to set `transfer = FALSE` to make this work?
Sorry to hear about the issue with the V2, the pipeline I'm working at the moment is really small and most of my research project are one off, so I often need to adapt everything every time... I had to modify some variable name due to the change in the nc file they provide... 
Thanks for your help!

**Comment by khufkens** [comment]
Thing is that the batch requests are there to do the handling of this more complicated stuff for you. So, no, there is not `transfer = FALSE` in this case, only for `wf_request()`. From what you write you want to schedule things and come back for a download. You can either do this by `wf_request()`, collect the URLs and come back later (when you estimate things done) OR you can use the RStudio job scheduler, so your console isn't tied up with `wf_batch_request()`. Alternatively, you can just open a terminal `R` session and late it sit there. These are about all the options.

**Comment by khufkens** [comment]
verbose output is now fixed per https://github.com/bluegreen-labs/ecmwfr/commit/805226fa771416e7da5082d3fb8cd7f1e2087463

**Comment by Rafnuss** [comment]
Hi @khufkens ,
Sorry, I haven't been following up on this close enough. But I'm still getting now filename in the output when using `wf_batch_request()` in my console log.

```r
  wf_transfer( # note that I'm using `wf_batch_request()` not `wf_request()`
   url = 'https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/3242e4c8-ce5d-4690-b672-30a690b30c4a',
   path = './data/wind/F11',
   filename = ''
  )
```

Can this be fixed or not at the enf?

Read again this thread,I do thing that using this function together with `job` is the best solution for my use case (https://raphaelnussbaumer.com/GeoPressureManual/geopressuretemplate-wind.html). Thanks a lot for your guidance.

**Comment by khufkens** [comment]
Did you update to the latest version? This should have been fixed at the `wf_request()` level.
